### ISSUE TITLE
Confirm Aethos Data

### ISSUE THREAD

**Issue by velvety-cc** [EigenExplorer/eigen-explorer-backend#234]
TVL and chart doesn't seem to match up.

<img src="https://uploads.linear.app/c34d2df9-2c1e-41ec-b6ca-d6457607ab26/0e371f6c-9615-4f8b-8911-6d640280f258/9f27f05e-d555-42de-8c20-4e1b37c9db9e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2MzNGQyZGY5LTJjMWUtNDFlYy1iNmNhLWQ2NDU3NjA3YWIyNi8wZTM3MWY2Yy05NjE1LTRmOGItODkxMS02ZDY0MDI4MGYyNTgvOWYyN2YwNWUtZDU1NS00MmRlLThjMjAtNGUxYjM3YzlkYjllIiwiaWF0IjoxNzI4MDc2MzA5LCJleHAiOjMzMjk4NjM2MzA5fQ.sWZ2GdMoaRbNVMRiv5VlGaL-7UJ7f7h6HYby5YbA4OM " alt="CleanShot 2024-10-04 at 14.11.07@2x.png" width="2458" height="2404" />

**Comment by uditdc** [comment]
Thanks for reporting! checking now
