### ISSUE TITLE
[Feat] - Operator Event History

### ISSUE THREAD

**Issue by velvety-cc** [EigenExplorer/eigen-explorer-backend#235]
API (or websocket?) to check the latest delegations for an operator

Example: I paste an operator address and get information about the most recent restakers for that operator, the amount of assets they deposited, the type of assets, etc

Thanks!

**Comment by uditdc** [comment]
There are 2 aspects to this:
- A single API that gives last {x} duration of events, ordered chronologically ... and/or grouped by hour/asset etc..
- A real-time socket that feeds events instantaneously.

@velvety-cc Do you prefer any one approach over the other ?

**Comment by velvety-cc** [comment]
Chorus One mentioned API would be better

**Comment by uditdc** [comment]
Nice! I'll draft the feature for this request.
