### ISSUE TITLE
Historical Count Routes - % change field

### ISSUE THREAD

**Issue by velvety-cc** [EigenExplorer/eigen-explorer-backend#89]
Add a % change field to the historical count routes.

**Comment by uditdc** [comment]
Include % change to the following routes:
1. /metrics/total-avs
2. /metrics/total-operators
3. /metrics/total-stakers

The updated format response will look like:
```
{
  "total": 100,
  "change24h": {
    "value": 5,
    "percent": 0.048
  },
  "change7d": {
    "value": -20,
    "percent": -0.18
  },
}
```

@velvety-cc please do let us know if this format suits the metrics count component on the FE. Thanks
